<?php

$currpage = 'Datenschutz';

?>

<?php include 'additional/head.php' ?>


<div class="content">

<div class="section terms-conditions wf-section">
   <div class="container-default w-container">
      <div class="terms-conditions-wrapper">
         <h1 data-w-id="c560f4c4-e9fd-b250-2704-3100ab99e527" style="transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); opacity: 1; transform-style: preserve-3d;" class="title terms-conditions">Datenschutz</h1>
         <div data-w-id="3c873e85-151f-2829-b0d9-b969a10660da" style="transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); opacity: 1; transform-style: preserve-3d;" class="rich-text w-richtext">

<p>
<strong>Disclaimer – rechtliche Hinweise</strong><br>
Soweit nachstehend keine anderen Angaben gemacht werden, ist die Bereitstellung Ihrer personenbezogenen Daten weder gesetzlich oder vertraglich vorgeschrieben, noch für einen Vertragsabschluss erforderlich. Sie sind zur Bereitstellung der Daten nicht verpflichtet. Eine Nichtbereitstellung hat keine Folgen. Dies gilt nur soweit bei den nachfolgenden Verarbeitungsvorgängen keine anderweitige Angabe gemacht wird. "Personenbezogene Daten" sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen.
<br><br>
<strong>Server-Logfiles</strong><br>
Sie können unsere Webseiten besuchen, ohne Angaben zu Ihrer Person zu machen. Bei jedem Zugriff auf unsere Website werden an uns oder unseren Webhoster / IT-Dienstleister Nutzungsdaten durch Ihren Internet Browser übermittelt und in Protokolldaten (sog. Server-Logfiles) gespeichert. Zu diesen gespeicherten Daten gehören z.B. der Name der aufgerufenen Seite, Datum und Uhrzeit des Abrufs, die IP-Adresse, die übertragene Datenmenge und der anfragende Provider. Die Verarbeitung erfolgt auf Grundlage des Art. 6 Abs. 1 lit. f DSGVO aus unserem überwiegenden berechtigten Interesse an der Gewährleistung eines störungsfreien Betriebs unserer Website sowie zur Verbesserung unseres Angebotes.
<br>
<br>
<strong>Bestellung bei Black-Host</strong><br>
Erhebung, Verarbeitung und Weitergabe personenbezogener Daten bei Bestellungen Bei der Bestellung erheben und verarbeiten wir Ihre personenbezogenen Daten nur, soweit dies zur Erfüllung und Abwicklung Ihrer Bestellung sowie zur Bearbeitung Ihrer Anfragen erforderlich ist. Die Bereitstellung der Daten ist für den Vertragsschluss erforderlich. Eine Nichtbereitstellung hat zur Folge, dass kein Vertrag geschlossen werden kann. Die Verarbeitung erfolgt auf Grundlage des Art. 6 Abs. 1 lit. b DSGVO und ist für die Erfüllung eines Vertrags mit Ihnen erforderlich. Eine Weitergabe Ihrer Daten erfolgt dabei beispielsweise an die von Ihnen gewählten Versandunternehmen und Dropshipping Anbieter, Zahlungsdienstleister, Diensteanbieter für die Bestellabwicklung und IT-Dienstleister. In allen Fällen beachten wir strikt die gesetzlichen Vorgaben. Der Umfang der Datenübermittlung beschränkt sich auf ein Mindestmaß.
<br><br>
 <strong>Kontakt</strong><br>
Erhebung und Verarbeitung bei Nutzung des Kontaktformulars
Bei der Nutzung des Kontaktformulars erheben wir Ihre personenbezogenen Daten (Name, E-Mail-Adresse, Nachrichtentext) nur in dem von Ihnen zur Verfügung gestellten Umfang. Die Datenverarbeitung dient dem Zweck der Kontaktaufnahme. Mit Absenden Ihrer Nachricht willigen Sie in die Verarbeitung der übermittelten Daten ein. Die Verarbeitung erfolgt auf Grundlage des Art. 6 Abs 1 lit. a DSGVO mit Ihrer Einwilligung.
Sie können Ihre Einwilligung jederzeit durch Mitteilung an uns widerrufen, ohne dass die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung berührt wird. Ihre E-Mail-Adresse nutzen wir nur zur Bearbeitung Ihrer Anfrage. Ihre Daten werden anschließend gelöscht, sofern Sie der weitergehenden Verarbeitung und Nutzung nicht zugestimmt haben. Verwendung der E-Mail-Adresse für die Zusendung von Direktwerbung
Wir nutzen Ihre E-Mail-Adresse, die wir im Rahmen des Verkaufes einer Ware oder Dienstleistung erhalten haben, für die elektronische Übersendung von Werbung für eigene Waren oder Dienstleistungen, die denen ähnlich sind, die Sie bereits bei uns erworben haben, soweit Sie dieser Verwendung nicht widersprochen haben. Die Bereitstellung der E-Mail-Adresse ist für den Vertragsschluss erforderlich. Eine Nichtbereitstellung hat zur Folge, dass kein Vertrag geschlossen werden kann. Die Verarbeitung erfolgt auf Grundlage des Art. 6 Abs. 1 lit. f DSGVO aus unserem überwiegenden berechtigten Interesse an Direktwerbung. Sie können dieser Verwendung Ihrer E-Mail-Adresse jederzeit durch Mitteilung an uns widersprechen. Die Kontaktdaten für die Ausübung des Widerspruchs finden Sie im Impressum. Sie können auch den dafür vorgesehenen Link in der Werbe-E-Mail nutzen. Hierfür entstehen keine anderen als die Übermittlungskosten nach den Basistarifen.
<br><br>
<strong>Zahlungsdienstleister</strong><br>
Verwendung von PayPal Alle PayPal-Transaktionen unterliegen der PayPal-Datenschutzerklärung. Diese finden Sie unter https://www.paypal.com/de/webapps/mpp/ua/privacy-prev?locale.x=de_DE Cookies Unsere Website verwendet Cookies. Cookies sind kleine Textdateien, die im Internetbrowser bzw. vom Internetbrowser auf dem Computersystem eines Nutzers gespeichert werden. Ruft ein Nutzer eine Website auf, so kann ein Cookie auf dem Betriebssystem des Nutzers gespeichert werden. Dieser Cookie enthält eine charakteristische Zeichenfolge, die eine eindeutige Identifizierung des Browsers beim erneuten Aufrufen der Website ermöglicht. Wir setzen Cookies zu dem Zweck ein, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen. Des Weiteren ermöglichen Cookies unseren Systemen, Ihren Browser auch nach einem Seitenwechsel zu erkennen und Ihnen Services anzubieten. Einige Funktionen unserer Internetseite können ohne den Einsatz von Cookies nicht angeboten werden. Für diese ist es erforderlich, dass der Browser auch nach einem Seitenwechsel wiedererkannt wird.
Wir verwenden auf unserer Website darüber hinaus Cookies zu dem Zweck, eine Analyse des Surfverhaltens unserer Seitenbesucher zu ermöglichen. Des Weiteren verwenden wir Cookies zu dem Zweck, Seitenbesucher anschließend auf anderen Webseiten mit gezielter, interessenbezogener Werbung anzusprechen. Die Verarbeitung erfolgt auf Grundlage des § 15 (3) TMG sowie Art. 6 (1) lit. f DSGVO aus dem berechtigten Interesse an den oben genannten Zwecken. Die auf diese Weise von Ihnen erhobenen Daten werden durch technische Vorkehrungen pseudonymisiert. Eine Zuordnung der Daten zu Ihrer Person ist daher nicht mehr möglich. Die Daten werden nicht gemeinsam mit sonstigen personenbezogenen Daten von Ihnen gespeichert. Sie haben das Recht aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit dieser auf Art. 6 (1) f DSGVO beruhenden Verarbeitung Sie betreffender personenbezogener Daten zu widersprechen. Cookies werden auf Ihrem Rechner gespeichert. Daher haben Sie die volle Kontrolle über die Verwendung von Cookies. Durch die Auswahl entsprechender technischer Einstellungen in Ihrem Internetbrowser können Sie die Speicherung der Cookies und Übermittlung der enthaltenen Daten verhindern. Bereits gespeicherte Cookies können jederzeit gelöscht werden. Wir weisen Sie jedoch darauf hin, dass Sie dann gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Unter den nachstehenden Links können Sie sich informieren, wie Sie die Cookies bei den wichtigsten Browsern verwalten (u.a. auch deaktivieren) können: <br>
Chrome Browser: https://support.google.com/accounts/answer/61416?hl=de <br>
Internet Explorer: https://support.microsoft.com/de-de/help/17442/windows-internet-explorer-delete-manage-cookies <br>
Mozilla Firefox: https://support.mozilla.org/de/kb/cookies-erlauben-und-ablehnen <br>
Safari: https://support.apple.com/de-de/guide/safari/manage-cookies-and-website-data-sfri11471/mac<br>
<br><br>
<strong>Nutzung von Google Analytics</strong><br>
Wir verwenden auf unserer Website den Webanalysedienst Google Analytics der Google Inc. (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; „Google“). Die Datenverarbeitung dient dem Zweck der Analyse dieser Website und ihrer Besucher. Dazu wird Google im Auftrag des Betreibers dieser Website die gewonnenen Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere, mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.
Google Analytics verwendet Cookies, die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch die Cookies erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Auf dieser Website ist die IP-Anonymisierung aktiviert. Dadurch wird Ihre IP-Adresse von Google innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Ihre Daten werden gegebenenfalls in die USA übermittelt. Für Datenübermittlungen in die USA ist ein Angemessenheitsbeschluss der Europäischen Kommission vorhanden. Die Verarbeitung erfolgt auf Grundlage des Art. 6 (1) lit. f DSGVO aus dem berechtigten Interesse an der bedarfsgerechten und zielgerichteten Gestaltung der Website. Sie haben das Recht aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit dieser auf Art. 6 (1) f DSGVO beruhenden Verarbeitung Sie betreffender personenbezogener Daten zu widersprechen. Sie können dazu die Speicherung der Cookies durch die Auswahl entsprechender technischer Einstellungen Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können des Weiteren die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plug-in herunterladen und installieren [https://tools.google.com/dlpage/gaoptout?hl=de]. Um die Erfassung durch Google Analytics geräteübergreifend zu verhindern können Sie einen Opt-Out-Cookie setzen. Opt-Out-Cookies verhindern die zukünftige Erfassung Ihrer Daten beim Besuch dieser Website. Sie müssen das Opt-Out auf allen genutzten Systemen und Geräten durchführen, damit dies umfassend wirkt. Wenn Sie hier klicken, wird das Opt-Out-Cookie gesetzt: Google Analytics deaktivieren. Nähere Informationen zu Nutzungsbedingungen und Datenschutz finden Sie unter https://www.google.com/analytics/terms/de.html bzw. unter https://www.google.de/intl/de/policies/. Verwendung der Remarketing- oder "Ähnliche Zielgruppen"-Funktion der Google Inc . Wir verwenden auf unserer Website die Remarketing- oder "Ähnliche Zielgruppen"- Funktion der Google Inc. (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; „Google“). Diese Funktion dient dem Zweck der Analyse des Besucherverhaltens und der Besucherinteressen.
Zur Durchführung der Analyse der Websiten-Nutzung, welche die Grundlage für die Erstellung der interessenbezogenen Werbeanzeigen bildet, setzt Google Cookies ein. Über die Cookies werden die Besuche der Website sowie anonymisierte Daten über die Nutzung der Website erfasst. Es erfolgt keine Speicherung von personenbezogenen Daten der Besucher der Website. Besuchen Sie nachfolgend eine andere Website im Google Display-Netzwerk werden Ihnen Werbeeinblendungen angezeigt, die mit hoher Wahrscheinlichkeit zuvor aufgerufene Produkt- und Informationsbereiche berücksichtigen. Ihre Daten werden dabei gegebenenfalls auch in die USA übermittelt. Für Datenübermittlungen in die USA ist ein Angemessenheitsbeschluss der Europäischen Kommission vorhanden. Die Verarbeitung erfolgt auf Grundlage des Art. 6 (1) lit. f DSGVO aus dem berechtigten Interesse, die Besucher der Website zielgerichtet mit Werbung anzusprechen, indem für Besucher der Website des Anbieters personalisierte, interessenbezogene Werbung-Anzeigen geschaltet werden, wenn sie andere Websiten im Google Display-Netzwerk besuchen. Sie haben das Recht aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit dieser auf Art. 6 (1) f DSGVO beruhenden Verarbeitung Sie betreffender personenbezogener Daten zu widersprechen.
Sie können dazu die Verwendung von Cookies durch Google dauerhaft deaktivieren, indem Sie dem nachfolgenden Link folgen und das dort bereitgestellte Plug-In herunterladen und installieren: https://support.google.com/ads/answer/7395996?hl=de Alternativ können Sie die Verwendung von Cookies durch Drittanbieter deaktivieren, indem sie die Deaktivierungsseite der Netzwerkwerbeinitiative (Network Advertising Initiative) unter https://www.networkadvertising.org/choices/ aufrufen und die dort genannten weiterführenden Information zum Opt-Out umsetzen. Nähere Informationen zu Google Remarketing sowie die dazugehörige Datenschutzerklärung finden Sie unter: https://www.google.com/privacy/ads/ Dazu können Sie die Speicherung der Cookies durch die Auswahl entsprechender technischer Einstellungen Ihrer Browser-Software verhindern. Wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie werden sodann nicht in die Conversion-Tracking Statistiken aufgenommen. Des Weiteren können Sie in den Einstellungen für Werbung bei Google für Sie personalisierte Werbung deaktivieren. Eine Anleitung dazu finden Sie unter https://support.google.com/ads/answer/2662922?hl=de Darüber hinaus können Sie die Verwendung von Cookies durch Drittanbieter deaktivieren, indem sie die Deaktivierungsseite der Netzwerkwerbeinitiative (Network Advertising Initiative) unter https://www.networkadvertising.org/choices/ aufrufen und die dort genannten weiterführenden Information zum Opt-Out umsetzen. Weiterführende Informationen sowie die Datenschutzerklärung von Google finden Sie unter: https://www.google.de/policies/privacy/
Plug-ins<br>
Verwendung von Social Plug-ins mittels „Shariff“<br>
Wir verwenden auf unserer Website Plug-ins sozialer Netzwerke. Damit Sie die Kontrolle über Ihre Daten behalten, nutzen wir die datenschutzsichere „Shariff"-Schaltflächen. Ohne Ihre ausdrückliche Zustimmung werden keine Verknüpfungen zu den Servern der sozialen Netzwerke hergestellt und folglich keine Daten übermittelt. „Shariff“ ist eine Entwicklung der Spezialisten der Computerzeitschrift c’t. Es ermöglicht mehr Privatsphäre im Netz und ersetzt die üblichen “Share”-Buttons der sozialen Netzwerke. Mehr Informationen zum Shariff-Projekt finden Sie hier https://www.heise.de/ct/artikel/Shariff-Social-Media-Buttons-mit-Datenschutz-2467514.html. Wenn Sie die Buttons anklicken erscheint ein Popup-Fenster, in dem Sie sich mit Ihren Daten beim jeweiligen Anbieter einloggen können. Erst nach diesem aktiven Login durch Sie wird eine direkte Verbindung zu den sozialen Netzwerken hergestellt.
Durch Ihr Login geben Sie Ihre Zustimmung zur Übertragung Ihrer Daten an den jeweiligen Social Media Anbieter. Hierbei werden u.a. sowohl Ihre IP-Adresse als auch die Information, welche unserer Seiten Sie besucht haben übermittelt. Sollten Sie gleichzeitig mit einem oder mehrerer Ihrer sozialen Netzwerk Konten verbunden sein, werden die gesammelten Informationen auch Ihren entsprechenden Profilen zugeordnet. Diese Zuordnung können Sie nur dadurch verhindern, dass Sie sich vor dem Besuch unserer Website und vor Aktivierung der Schaltflächen aus Ihren Social Media Konten ausloggen. Nachstehend benannte soziale Netzwerke sind mittels der "Shariff"-Funktion eingebunden. Nähere Informationen zu Umfang und Zweck der Erhebung und Nutzung der Daten sowie über Ihre diesbezüglichen Rechte und Möglichkeiten zum Schutz Ihrer Privatsphäre finden Sie in den verlinkten Datenschutzhinweisen der Anbieter.
<br><br>
<strong>Verwendung von GoogleMaps</strong><br>
Wir verwenden auf unserer Website die Funktion zur Einbettung von GoogleMaps-Karten der Google Inc. (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; “Google”). Die Funktion ermöglicht die visuelle Darstellung von geographischen Informationen und interaktiven Landkarten. Dabei werden von Google bei Aufrufen der Seiten, in die GoogleMaps-Karten eingebunden sind, auch Daten der Besucher der Websites erhoben, verarbeitet und genutzt. Ihre Daten werden dabei gegebenenfalls auch in die USA übermittelt. Google hat sich nach dem US-EU-Datenschutzabkommen “Privacy Shield” zertifiziert und damit verpflichtet, die europäischen Datenschutzrichtlinien einzuhalten.
Die Verarbeitung erfolgt auf Grundlage des Art. 6 Abs. 1 lit. f DSGVO aus dem berechtigten Interesse an der bedarfsgerechten und zielgerichteten Gestaltung unserer Website. Nähere Informationen zur Erhebung und Nutzung der Daten durch Google finden Sie in den Datenschutzhinweisen von Google unter https://www.google.com/privacypolicy.html. Dort haben Sie auch im Datenschutzcenter die Möglichkeit Ihre Einstellungen zu verändern, so dass Sie Ihre von Google verarbeiteten Daten verwalten und schützen können. Verwendung von Google reCAPTCHA Wir verwenden auf unserer Website den Dienst reCAPTCHA der Google Inc. (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; „Google“). Die Abfrage dient dem Zweck der Unterscheidung der Eingabe durch einen Menschen oder durch automatisierte, maschinelle Verarbeitung. Dazu wird Ihre Eingabe an Google übermittelt und dort weiterverwendet. Zusätzlich werden die IP-Adresse und gegebenenfalls weitere von Google für den Dienst reCAPTCHA benötigte Daten an Google übertragen. Diese Daten werden von Google innerhalb der Europäischen Union verarbeitet und gegebenenfalls auch in die USA übermittelt. Google hat sich nach dem US-EU-Datenschutzabkommen “Privacy Shield” zertifiziert und damit verpflichtet, die europäischen Datenschutzrichtlinien einzuhalten. Die Verarbeitung erfolgt auf Grundlage des Art. 6 Abs. 1 lit. f DSGVO aus dem berechtigten Interesse unsere Website vor automatisierter Ausspähung, Missbrauch und SPAM zu schützen. Nähere Informationen zu Google reCAPTCHA sowie die dazugehörige Datenschutzerklärung finden Sie unter: https://www.google.com/recaptcha/intro/android.html sowie https://www.google.com/privacy. Betroffenenrechte und Speicherdauer Dauer der Speicherung Nach vollständiger Vertragsabwicklung werden die Daten zunächst für die Dauer der Gewährleistungsfrist, danach unter Berücksichtigung gesetzlicher, insbesondere steuer- und handelsrechtlicher Aufbewahrungsfristen gespeichert und dann nach Fristablauf gelöscht, sofern Sie der weitergehenden Verarbeitung und Nutzung nicht zugestimmt haben.
<br><br>
<strong>Beschwerderecht bei der Aufsichtsbehörde</strong><br>
Sie haben gemäß Art. 77 DSGVO das Recht, sich bei der Aufsichtsbehörde zu beschweren, wenn Sie der Ansicht sind, dass die Verarbeitung Ihrer personenbezogenen Daten nicht rechtmäßig erfolgt. Widerspruchsrecht
Beruhen die hier aufgeführten personenbezogenen Datenverarbeitungen auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO, haben Sie das Recht aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit diesen Verarbeitungen mit Wirkung für die Zukunft zu widersprechen. Nach erfolgtem Widerspruch wird die Verarbeitung der betroffenen Daten beendet, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihren Interessen, Rechten und Freiheiten überwiegen, oder wenn die Verarbeitung der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen dient.
Erfolgt die personenbezogene Datenverarbeitung zu Zwecken der Direktwerbung, können Sie dieser Verarbeitung jederzeit durch Mitteilung an uns widersprechen. Nach erfolgtem Widerspruch beenden wir die Verarbeitung der betroffenen Daten zum Zwecke der Direktwerbung.

<br><br>

<strong>Verwendung von Tawk</strong><br>
Wir verwenden global die Livechat-Software Tawk, der Datenschutz ist hier zu finden: https://www.tawk.to/privacy-policy/
</p>


         </div>
      </div>
   </div>
</div>

</div>

<?php include 'additional/footer.php' ?>